name: Cursor Utilization → Port

on:
  schedule:
    - cron: '15 2 * * *' # daily at 02:15 UTC
  workflow_dispatch:
    inputs:
      mode:
        description: 'daily or backfill'
        required: false
        default: 'daily'
      days:
        description: 'number of days to process'
        required: false
        default: '1'
      with_relations:
        description: 'Include Port relations between entities'
        required: false
        default: false
        type: boolean

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      - name: Run ingestion
        env:
          X_CURSOR_API_KEY: ${{ secrets.X_CURSOR_API_KEY }}
          PORT_CLIENT_ID: ${{ secrets.PORT_CLIENT_ID }}
          PORT_CLIENT_SECRET: ${{ secrets.PORT_CLIENT_SECRET }}
          PORT_BASE_URL: ${{ vars.PORT_BASE_URL || 'https://api.getport.io' }}
          PORT_AUTH_URL: ${{ vars.PORT_AUTH_URL || 'https://api.getport.io/v1/auth/access_token' }}
          ORG_IDENTIFIER: ${{ vars.ORG_IDENTIFIER }}
          TIMEZONE: UTC
          LOOKBACK_DAYS: 1
          DRY_RUN: false
        run: |
          source .venv/bin/activate
          python -m src.main --mode "${{ inputs.mode || 'daily' }}" --days "${{ inputs.days || '1' }}" ${{ inputs.with_relations == true && '--with-relations' || '' }}


